-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 10:31:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shoppingSite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoppingSite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingSite` DEFAULT CHARACTER SET utf8 ;
USE `shoppingSite` ;

-- -----------------------------------------------------
-- Table `shoppingSite`.`tblRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblRoles` (
  `fldRole_ID` INT NOT NULL AUTO_INCREMENT,
  `fldRoleName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`fldRole_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblUser` (
  `fldUser_ID` INT NOT NULL AUTO_INCREMENT,
  `fldFirstName` VARCHAR(32) NOT NULL,
  `fldLastName` VARCHAR(32) NULL,
  `fldEmail` VARCHAR(100) NOT NULL,
  `fldPhone` VARCHAR(15) NOT NULL,
  `fldRoleId` INT NOT NULL,
  `fldHashedPassword` VARCHAR(256) NOT NULL,
  `fldUserSaltString` VARCHAR(32) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldUpdatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `fldUpdatedBy` INT NULL,
  PRIMARY KEY (`fldUser_ID`),
  INDEX `roleId_idx` (`fldRoleId` ASC) INVISIBLE,
  UNIQUE INDEX `email_idx` (`fldEmail` ASC) INVISIBLE,
  INDEX `phoneNumber_idx` (`fldPhone` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedBy` ASC) VISIBLE,
  CONSTRAINT `roleId`
    FOREIGN KEY (`fldRoleId`)
    REFERENCES `shoppingSite`.`tblRoles` (`fldRole_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `updatedBy`
    FOREIGN KEY (`fldUpdatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblAddress` (
  `fldAddress_ID` INT NOT NULL AUTO_INCREMENT,
  `fldUserId` INT NOT NULL,
  `fldFirstName` VARCHAR(32) NOT NULL,
  `fldLastName` VARCHAR(32) NULL,
  `fldAddressLine1` VARCHAR(64) NOT NULL,
  `fldAddressLine2` VARCHAR(64) NOT NULL,
  `fldCity` VARCHAR(64) NOT NULL,
  `fldState` VARCHAR(64) NOT NULL,
  `fldPincode` VARCHAR(10) NOT NULL,
  `fldPhoneNumber` VARCHAR(15) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldDeactivatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldAddress_ID`),
  INDEX `userid_idx` (`fldUserId` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblOrder` (
  `fldOrder_ID` VARCHAR(64) NOT NULL,
  `fldUserId` INT NOT NULL,
  `fldAddressId` INT NOT NULL,
  `fldTotalPrice` DECIMAL(10,2) NOT NULL,
  `fldTotalTax` DECIMAL(10,2) NOT NULL,
  `fldCardPart` VARCHAR(4) NOT NULL,
  `fldOrderDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldOrder_ID`),
  INDEX `tblOrder_userid_idx` (`fldUserId` ASC) VISIBLE,
  INDEX `addressId_idx` (`fldAddressId` ASC) VISIBLE,
  CONSTRAINT `tblOrder_userid`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addressId`
    FOREIGN KEY (`fldAddressId`)
    REFERENCES `shoppingSite`.`tblAddress` (`fldAddress_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblCategory` (
  `fldCategory_ID` INT NOT NULL AUTO_INCREMENT,
  `fldCategoryName` VARCHAR(64) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldCreatedBy` INT NOT NULL,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldCategory_ID`),
  INDEX `createdBy_idx` (`fldCreatedBy` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedBy` ASC) VISIBLE,
  CONSTRAINT `createdBy`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblCategory_updatedBy`
    FOREIGN KEY (`fldUpdatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblSubCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblSubCategory` (
  `fldSubCategory_ID` INT NOT NULL AUTO_INCREMENT,
  `fldCategoryId` INT NOT NULL,
  `fldSubCategoryName` VARCHAR(64) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldCreatedBy` INT NOT NULL,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldSubCategory_ID`),
  INDEX `categoryId_idx` (`fldCategoryId` ASC) VISIBLE,
  INDEX `createdby_idx` (`fldCreatedBy` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedBy` ASC) VISIBLE,
  CONSTRAINT `categoryId`
    FOREIGN KEY (`fldCategoryId`)
    REFERENCES `shoppingSite`.`tblCategory` (`fldCategory_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblSubCategory_createdBy`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblSubCategory_updatedBy`
    FOREIGN KEY (`fldUpdatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblBrands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblBrands` (
  `fldBrand_ID` INT NOT NULL AUTO_INCREMENT,
  `fldBrandName` VARCHAR(64) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`fldBrand_ID`),
  INDEX `brandName` (`fldBrandName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblProduct` (
  `fldProduct_ID` INT NOT NULL AUTO_INCREMENT,
  `fldSubCategoryId` INT NOT NULL,
  `fldProductName` VARCHAR(100) NOT NULL,
  `fldBrandId` INT NOT NULL,
  `fldDescription` TEXT NULL,
  `fldPrice` DECIMAL(10,2) NOT NULL,
  `fldTax` DECIMAL(10,2) NOT NULL,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldCreatedBy` INT NOT NULL,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldProduct_ID`),
  INDEX `subcategoryId_idx` (`fldSubCategoryId` ASC) VISIBLE,
  INDEX `createdBy_idx` (`fldCreatedBy` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedBy` ASC) VISIBLE,
  INDEX `productName_idx` (`fldProductName` ASC) INVISIBLE,
  INDEX `brandId_idx` (`fldBrandId` ASC) VISIBLE,
  CONSTRAINT `subcategoryId`
    FOREIGN KEY (`fldSubCategoryId`)
    REFERENCES `shoppingSite`.`tblSubCategory` (`fldSubCategory_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblProduct_createdBy`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblProduct_updatedBy`
    FOREIGN KEY (`fldUpdatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `brandId`
    FOREIGN KEY (`fldBrandId`)
    REFERENCES `shoppingSite`.`tblBrands` (`fldBrand_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblOrderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblOrderItems` (
  `fldOrderItem_ID` INT NOT NULL AUTO_INCREMENT,
  `fldOrderId` VARCHAR(64) NOT NULL,
  `fldProductId` INT NOT NULL,
  `fldQuantity` INT NOT NULL,
  `fldUnitPrice` DECIMAL(10,2) NOT NULL,
  `fldUnitTax` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`fldOrderItem_ID`),
  INDEX `orderId_idx` (`fldOrderId` ASC) VISIBLE,
  INDEX `productId_idx` (`fldProductId` ASC) VISIBLE,
  CONSTRAINT `orderId`
    FOREIGN KEY (`fldOrderId`)
    REFERENCES `shoppingSite`.`tblOrder` (`fldOrder_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productId`
    FOREIGN KEY (`fldProductId`)
    REFERENCES `shoppingSite`.`tblProduct` (`fldProduct_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblProductImages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblProductImages` (
  `fldProductImage_ID` INT NOT NULL AUTO_INCREMENT,
  `fldProductId` INT NOT NULL,
  `fldImageFileName` VARCHAR(128) NOT NULL,
  `fldDefaultImage` TINYINT(1) NULL DEFAULT 0,
  `fldCreatedBy` INT NOT NULL,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fldActive` TINYINT(1) NOT NULL DEFAULT 1,
  `fldUpdatedBy` INT NULL,
  `fldUpdatedDate` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldProductImage_ID`),
  INDEX `productId_idx` (`fldProductId` ASC) VISIBLE,
  INDEX `createdby_idx` (`fldCreatedBy` ASC) VISIBLE,
  INDEX `updatedBy_idx` (`fldUpdatedBy` ASC) VISIBLE,
  CONSTRAINT `tblProductImages_productId`
    FOREIGN KEY (`fldProductId`)
    REFERENCES `shoppingSite`.`tblProduct` (`fldProduct_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblProductImages_createdby`
    FOREIGN KEY (`fldCreatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblProductImages_updatedBy`
    FOREIGN KEY (`fldUpdatedBy`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoppingSite`.`tblCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingSite`.`tblCart` (
  `fldCart_ID` INT NOT NULL AUTO_INCREMENT,
  `fldUserId` INT NOT NULL,
  `fldProductId` INT NOT NULL,
  `fldQuantity` INT NOT NULL,
  `fldCreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fldCart_ID`),
  INDEX `createdBy_idx` (`fldUserId` ASC) VISIBLE,
  INDEX `productId_idx` (`fldProductId` ASC) VISIBLE,
  CONSTRAINT `tblCart_createdBy`
    FOREIGN KEY (`fldUserId`)
    REFERENCES `shoppingSite`.`tblUser` (`fldUser_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tblCart_productId`
    FOREIGN KEY (`fldProductId`)
    REFERENCES `shoppingSite`.`tblProduct` (`fldProduct_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `shoppingSite`.`tblRoles`
-- -----------------------------------------------------
START TRANSACTION;
USE `shoppingSite`;
INSERT INTO `shoppingSite`.`tblRoles` (`fldRole_ID`, `fldRoleName`) VALUES (1, 'Admin');
INSERT INTO `shoppingSite`.`tblRoles` (`fldRole_ID`, `fldRoleName`) VALUES (2, 'User');

COMMIT;


-- -----------------------------------------------------
-- Data for table `shoppingSite`.`tblBrands`
-- -----------------------------------------------------
START TRANSACTION;
USE `shoppingSite`;
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (1, 'Adidas', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (2, 'Puma', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (3, 'Nike', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (4, 'Peter England', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (5, 'Levi\'s', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (6, 'Samsung', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (7, 'Vivo ', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (8, 'Apple', 1);
INSERT INTO `shoppingSite`.`tblBrands` (`fldBrand_ID`, `fldBrandName`, `fldActive`) VALUES (9, 'Others', 1);

COMMIT;